[project]
name = "mindset-growth-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
python = ">=3.10"

dependencies = [
  "streamlit>=1.31.0",
  "pandas>=1.3.0",
  "openpyxl"
]



